### ISSUE TITLE
(Version 4.2.2) Occasionally getting a java heap space error when running the network intercept too often

### ISSUE THREAD

**Issue by chadbellangivelify** [webdriverio-community/wdio-intercept-service#417]
0-4] 2022-10-24T15:47:01.900Z ERROR webdriver: Request failed with status 500 due to unknown error: Java heap space
[0-4] unknown error in "Givelify Analytics Studio - Campus dropdown.Validate campus navigation"
unknown error: Java heap space
    at runMicrotasks (<anonymous>)
    at getRequest (/srv/analytics-studio-automated-tester/releases/20221021150513/node_modules/wdio-intercept-service/index.js:266:37)
    at Browser.getRequests (/srv/analytics-studio-automated-tester/releases/20221021150513/node_modules/wdio-intercept-service/index.js:262:14)
    at Function.getNetworkResponse (/srv/analytics-studio-automated-tester/releases/20221021150513/helpers/utilities.js:410:43)

**Comment by chadbellangivelify** [comment]
I am no longer seeing this error
