### ISSUE TITLE
Exception in .getRequests

### ISSUE THREAD

**Issue by shashikdm** [webdriverio-community/wdio-intercept-service#464]
### Stacktrace
```
TypeError: Cannot read property 'trim' of undefined
    at parseResponseHeaders (/Users/shashikant/webdriverio-tests/node_modules/wdio-intercept-service/index.js:353:32)
    at transformRequest (/Users/shashikant/webdriverio-tests/node_modules/wdio-intercept-service/index.js:328:20)
    at Array.map (<anonymous>)
    at Browser.getRequest (/Users/shashikant/webdriverio-tests/node_modules/wdio-intercept-service/index.js:296:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Browser.wrapCommandFn (/Users/shashikant/webdriverio-tests/node_modules/@wdio/utils/build/shim.js:137:29)
```
### How to reproduce?
```
browser.url('https://amazon.com/');
await browser.pause(3000);
await browser.setupInterceptor();
console.log("After interceptor")

await browser.pause(3000);

await browser.expectRequest('HEAD', '/api/2017/suggestions', 204);

let searchSuggestions = await browser.getRequests();
console.log('Suggestions From API: ', searchSuggestions);
```
### Expected behaviour
Get list of request objects
### Actual behaviour
Throws error mentioned above
### Version
```
wdio-intercept-service@4.3.0
```

**Comment by shashikdm** [comment]
it seems that if the headers field is empty then it is breaking
I put a log line before this https://github.com/webdriverio-community/wdio-intercept-service/blob/6e62164cbea24198517dc02253aeff24e0529442/index.js#L348
```
[0-0]   {
[0-0]     __fulfilled: 1671532867458,
[0-0]     __processed: 1671532867383,
[0-0]     body: '',
[0-0]     headers: '',
[0-0]     method: 'GET',
[0-0]     requestHeaders: '',
[0-0]     statusCode: 0,
[0-0]     url: 'https://dr3fr5q4g2ul9.cloudfront.net?814af276-da31-8eca-afd7-1dc5f672075b'
[0-0]   },
```

**Comment by tehhowch** [comment]
@shashikdm please verify if v4.3.1 fixes the issue. The work in #438 should resolve this error.

If the latest release fixes the issue, please close the issue :+1:

**Comment by shashikdm** [comment]
can confirm v4.3.1 has fixed the issue. thank you!
